### ISSUE TITLE
How to do multi-turn

### ISSUE THREAD

**Issue by HuanzhiMao** [SalesforceAIResearch/xLAM#7]
Hey there, 
Thank you for the great models. 
I'm wondering if the xLAM models support multi-turn (eg, user -> assistant -> tool result -> assistant)? If so, how should I format the query message?

**Comment by jianguoz** [comment]
Hi @HuanzhiMao, Thanks for raising the question! We are updating our templates and will let you know in the upcoming 3-4 days.

**Comment by HuanzhiMao** [comment]
> Hi @HuanzhiMao, Thanks for raising the question! We are updating our multi-turn templates and will let you know in the upcoming 3-4 days.

Perfect. Thank you!

**Comment by jianguoz** [comment]
Hi @HuanzhiMao, we've completed the updates for the multi-turn templates and models. We'll proceed with the public release once the leadership team approves the changes.

**Comment by HuanzhiMao** [comment]
Any updates on this?

**Comment by zuxin666** [comment]
Hi @HuanzhiMao , we have recently add an [xLAM client](https://github.com/SalesforceAIResearch/xLAM/blob/main/xLAM/client/xLAM.py) to handle the multi-turn messages. The instruction [here](https://github.com/SalesforceAIResearch/xLAM/tree/main#using-the-chat-completion-api) shows an example usage. Would that be helpful?

**Comment by HuanzhiMao** [comment]
> Hi @HuanzhiMao , we have recently add an [xLAM client](https://github.com/SalesforceAIResearch/xLAM/blob/main/xLAM/client/xLAM.py) to handle the multi-turn messages. The instruction [here](https://github.com/SalesforceAIResearch/xLAM/tree/main#using-the-chat-completion-api) shows an example usage. Would that be helpful?

Yes. That's exactly what I'm looking for. Thank you!
